name: Jenkins Release

on: 
  workflow_dispatch: 
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: ghcr.io/mohamed-rafraf/kn-jenkins
  IMAGE_TAG: v0.0.0-0.0.0

jobs:
  jenkins-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Jenkins Image
        id: vars
        run: echo "IMAGE_TAG=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v[0-9]*\.[0-9]*\.[0-9]*-//')" >> $GITHUB_ENV
      
      - name: Use IMAGE_TAG
        run: |
          echo "Using IMAGE_TAG $IMAGE_TAG"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set short hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build & Push image
        run: |
          echo "Building Jenkins Version $IMAGE_TAG"
          make release-jenkins JENKINS_VERSION=${{ steps.vars.outputs.sha_short }} IMAGE_NAME=$IMAGE_NAME
